"""
UGE/SGE script templates.

These templates replace the hardcoded .sh files with configurable Python-generated scripts.
"""

# Array job template for chunked processing
ARRAY_JOB_TEMPLATE = '''#!/bin/bash
# UGE array job script - generated by max_info_atlases
#$ -cwd
#$ -o {logs_dir}/{job_name}.$JOB_ID.$TASK_ID.log
#$ -j y
#$ -l h_data={memory},h_rt={runtime}
#$ -N {job_name}
#$ -t 1-{num_chunks}

set -e

# Load environment
. {module_init}
module load conda
conda activate {conda_env}

# Find chunk file for this task
chunk_file=$(ls {chunks_dir}/chunk_$(printf "%04d" $SGE_TASK_ID)_of_*.txt 2>/dev/null | head -1)

if [ -z "$chunk_file" ]; then
    echo "Error: No chunk file found for SGE_TASK_ID $SGE_TASK_ID"
    echo "Looking for pattern: chunk_$(printf "%04d" $SGE_TASK_ID)_of_*.txt"
    exit 1
fi

echo "Processing chunk: $chunk_file"
echo "Task ID: $SGE_TASK_ID"
echo "Start time: $(date)"

# Run the worker with the specified command
{worker_command}

echo "End time: $(date)"
echo "Done SGE_TASK_ID $SGE_TASK_ID"
'''

# Single job template for resubmits
SINGLE_JOB_TEMPLATE = '''#!/bin/bash
# UGE single job script (resubmit) - generated by max_info_atlases
#$ -cwd
#$ -o {logs_dir}/resubmit_{chunk_id}.$JOB_ID.log
#$ -j y
#$ -l h_data={memory},h_rt={runtime}
#$ -N resubmit_{chunk_id}

set -e

# Load environment
. {module_init}
module load conda
conda activate {conda_env}

echo "Resubmit job for chunk: {chunk_id}"
echo "Chunk file: {chunk_file}"
echo "Start time: $(date)"

# Run the worker
python -m max_info_atlases.cli worker \\
    --chunk-file "{chunk_file}" \\
    --base-dir "{base_dir}" \\
    --output-dir "{temp_dir}"

echo "End time: $(date)"
echo "Done resubmit chunk {chunk_id}"
'''

# Clustering job template
CLUSTERING_JOB_TEMPLATE = '''#!/bin/bash
# UGE clustering job - generated by max_info_atlases
#$ -cwd
#$ -o {logs_dir}/{job_name}.$JOB_ID.$TASK_ID.log
#$ -j y
#$ -l h_data={memory},h_rt={runtime}
#$ -N {job_name}
#$ -t 1-{num_jobs}

set -e

# Load environment
. {module_init}
module load conda
conda activate {conda_env}

# Get job line from job file
job_line=$(sed -n "${{SGE_TASK_ID}}p" {job_file})

if [ -z "$job_line" ]; then
    echo "Error: No job line for SGE_TASK_ID $SGE_TASK_ID"
    exit 1
fi

echo "Processing job: $job_line"
echo "Task ID: $SGE_TASK_ID"
echo "Start time: $(date)"

# Parse and run the job
{command_prefix} $job_line

echo "End time: $(date)"
echo "Done SGE_TASK_ID $SGE_TASK_ID"
'''

# Default UGE settings
DEFAULT_UGE_SETTINGS = {
    'module_init': '/u/local/Modules/default/init/modules.sh',
    'conda_env': 'max_info_atlases',
    'memory': '16G',
    'runtime': '4:00:00',
    'resubmit_memory': '16G',
    'resubmit_runtime': '2:00:00',
}


def generate_array_job_script(
    chunks_dir: str,
    num_chunks: int,
    job_name: str,
    base_dir: str,
    temp_dir: str,
    logs_dir: str,
    memory: str = None,
    runtime: str = None,
    conda_env: str = None,
    module_init: str = None,
    worker_command: str = None,
) -> str:
    """
    Generate an array job script for chunked processing.
    
    Args:
        chunks_dir: Directory containing chunk files
        num_chunks: Number of chunks (tasks)
        job_name: Name for the job
        base_dir: Base directory for input data
        temp_dir: Directory for temporary outputs
        logs_dir: Directory for log files
        memory: Memory request (default: 16G)
        runtime: Runtime request (default: 4:00:00)
        conda_env: Conda environment name
        module_init: Path to modules init script
        worker_command: Custom worker command (default: max-info worker)
        
    Returns:
        Generated script content
    """
    if worker_command is None:
        worker_command = f'''max-info worker \\
    --chunk-file "$chunk_file" \\
    --base-dir "{base_dir}" \\
    --output-dir "{temp_dir}"'''
    
    return ARRAY_JOB_TEMPLATE.format(
        chunks_dir=chunks_dir,
        num_chunks=num_chunks,
        job_name=job_name,
        base_dir=base_dir,
        temp_dir=temp_dir,
        logs_dir=logs_dir,
        memory=memory or DEFAULT_UGE_SETTINGS['memory'],
        runtime=runtime or DEFAULT_UGE_SETTINGS['runtime'],
        conda_env=conda_env or DEFAULT_UGE_SETTINGS['conda_env'],
        module_init=module_init or DEFAULT_UGE_SETTINGS['module_init'],
        worker_command=worker_command,
    )


def generate_single_job_script(
    chunk_file: str,
    chunk_id: str,
    base_dir: str,
    temp_dir: str,
    logs_dir: str,
    memory: str = None,
    runtime: str = None,
    conda_env: str = None,
    module_init: str = None,
) -> str:
    """
    Generate a single job script for resubmitting a failed chunk.
    
    Args:
        chunk_file: Path to the chunk file
        chunk_id: Identifier for the chunk
        base_dir: Base directory for input data
        temp_dir: Directory for temporary outputs
        logs_dir: Directory for log files
        memory: Memory request
        runtime: Runtime request
        conda_env: Conda environment name
        module_init: Path to modules init script
        
    Returns:
        Generated script content
    """
    return SINGLE_JOB_TEMPLATE.format(
        chunk_file=chunk_file,
        chunk_id=chunk_id,
        base_dir=base_dir,
        temp_dir=temp_dir,
        logs_dir=logs_dir,
        memory=memory or DEFAULT_UGE_SETTINGS['resubmit_memory'],
        runtime=runtime or DEFAULT_UGE_SETTINGS['resubmit_runtime'],
        conda_env=conda_env or DEFAULT_UGE_SETTINGS['conda_env'],
        module_init=module_init or DEFAULT_UGE_SETTINGS['module_init'],
    )
